name: 🚀 Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH connection
        run: |
          ssh -v -o StrictHostKeyChecking=no -p 1022 ${{ secrets.SSH_USERNAME }}@mykhailodorokhov.ee

      - name: Run git pull
        run: |
          ssh -v -o StrictHostKeyChecking=no -p 1022 ${{ secrets.SSH_USERNAME }}@mykhailodorokhov.ee << 'EOF'
            cd htdocs
            git pull
          EOF