name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to SSH Server
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: mykhailodorokhov.ee
        username: ${{ secrets.SSH_USERNAME }}
        password: $({ secrets.SSH_PASSWORD })
        port: 1022
        script: |
          cd htdocs
          git pull origin main
