name: Deploy Homepage

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to FTP Server
      uses: SamKirkland/FTP-Deploy-Action@4.3.4
      with:
        server: ftp://mykhailodorokhov.ee.klient.veebimajutus.ee
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /htdocs/
